services:
  app:
    build: ./Web
    environment:
      - NODE_ENV=production
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: pass1234
      MONGO_INITDB_DATABASE: RubrITM
    expose:
      - "27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: